/* eslint-disable react/jsx-no-comment-textnodes */
import Head from "next/head";
import { Menu } from "ui";
import { TitlePylar } from "ui";
import { Footer } from "ui";
import { motion } from "framer-motion";
import { Contact } from "ui";

export default function Home() {
  console.log("✅ Pylar AI");
  return (
    <div className="min-w-screen flex min-h-screen flex-col bg-black">
      <Head>
        <title>Pylar AI by Pencil</title>
        <link rel="icon" href="./favicon.ico" />
      </Head>
      <Menu />
      <main>
        <TitlePylar />
        <div>
          <p className="p-16 text-justify text-2xl text-white">
            Pylar is a research organization that focuses on the development and
            application of AI technology. The organization uses stable diffusion
            algorithms and private models to generate generative images and
            other data. Pylar offers a prompt-based AI service, which allows
            customers to provide input data and generate customized results
            using the organization advanced AI technology. Pylar may generate
            revenue through licensing its technology, selling the data generated
            by its AI, and partnering with academic institutions and research
            organizations.
          </p>

          <p className="p-16 text-justify text-2xl text-white">
            Pylar is a research organization focused on the development and
            application of AI technology. Through the use of stable diffusion
            algorithms and private models, Pylar aims to generate generative
            images and other data. The organization offers a prompt-based AI
            service, which allows customers to provide specific input data and
            generate customized results using Pylar advanced AI technology.
            Pylar may generate revenue through licensing its technology, selling
            the images and data generated by its AI, and partnering with
            academic institutions and research organizations.
          </p>
          <Contact />
        </div>
      </main>
      <Footer />
    </div>
  );
}
